sudo: true
dist: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- openssl aes-256-cbc -K $encrypted_65674265f95b_key -iv $encrypted_65674265f95b_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=true
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- wget -qO- $URL | tar xJf -
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx update
- sfdx force:auth:jwt:grant --clientid $CONSUMER_KEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a HubOrg
- mv force-app/main/test/* force-app/main/default/classes
script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg -c -r human
- touch test-runners/DiscoveryTestRunner.apex
- echo "IBMDiscoveryV1FTests.runAllTests($DISCOVERY_USERNAME, $DISCOVERY_PASSWORD);" > test-runners/DiscoveryTestRunner.apex
- sfdx force:apex:execute -f test-runners/DiscoveryTestRunner.apex
- rm test-runners/DiscoveryTestRunner.apex
- sfdx force:org:delete -u ciorg -p
- mv install/package.xml force-app/main/default
- "./install/deploy.sh"
